const vm=require('node:vm'),assert=require('node:assert/strict');
const {constants:C,readSource}=require('./test-support/runtime.cjs');
const logs=[],ctx={...C,module:{exports:{}},console:{log:s=>logs.push(s)},Memory:{frontier:{rooms:{R:{plan:{complete:true,roadVersion:1,roadMissing:[],structures:[{type:C.STRUCTURE_ROAD,x:21,y:21,roadClass:'economy',roadSwamp:true},{type:C.STRUCTURE_ROAD,x:22,y:22,roadClass:'economy',roadSwamp:false}],roadRoutes:[{id:'source:s',tiles:[1071,1122],complete:true}]}}}}},Game:{time:20,creeps:{},cpu:{getUsed:()=>5,bucket:10000,limit:20}}};
vm.createContext(ctx);
ctx.ledgerModule={exports:{}};
vm.runInContext('(function(module){'+readSource('ledger.js')+'})(ledgerModule);',ctx);
ctx.require=name=>{assert.equal(name,'ledger');return ctx.ledgerModule.exports;};
vm.runInContext(readSource('monitor.js'),ctx);
const pos=(x,y)=>({x,y,roomName:'R'}),store=(energy,capacity)=>({energy,getCapacity:()=>capacity,getFreeCapacity(){return capacity-this.energy;}});
const source={id:'s',pos:pos(20,20),energy:3000,energyCapacity:3000,ticksToRegeneration:280};
const box={id:'box',structureType:C.STRUCTURE_CONTAINER,pos:pos(21,20),store:store(2000,2000)};
const drop={id:'drop',resourceType:C.RESOURCE_ENERGY,pos:pos(21,20),amount:1200};
const road={id:'road',structureType:C.STRUCTURE_ROAD,pos:pos(21,21)};
const site={id:'site',structureType:C.STRUCTURE_ROAD,pos:pos(22,22),progress:100,progressTotal:300};
const room={name:'R',controller:{level:2,progress:1000,progressTotal:45000,ticksToDowngrade:10000},energyAvailable:550,energyCapacityAvailable:550,getTerrain:()=>({get:()=>0}),find(type,opt){const a=type===C.FIND_SOURCES?[source]:type===C.FIND_STRUCTURES?[box,road]:type===C.FIND_DROPPED_RESOURCES?[drop]:type===C.FIND_MY_CONSTRUCTION_SITES?[site]:[];return opt&&opt.filter?a.filter(opt.filter):a;}};
function unit(name,role,x,y,work=0,spawning=false){const u={id:name,name,my:true,memory:{home:'R',role,source:'s',loaded:true,stuck:0},pos:pos(x,y),spawning,ticksToLive:1000,fatigue:0,store:store(250,250),body:Array(work).fill(null).map(()=>({type:C.WORK,hits:100})).concat({type:C.CARRY,hits:100},{type:C.MOVE,hits:100}),getActiveBodyparts:t=>t===C.WORK?work:1};ctx.Game.creeps[name]=u;return u;}
unit('working','miner',21,20,4);unit('replacement','miner',10,10,4);unit('spawning','miner',21,20,4,true);
const hauler=unit('haul','hauler',22,24);
const tick=t=>{ctx.Game.time=t;ctx.module.exports.tick([room]);return ctx.Memory.frontier.telemetry.rooms.R;};
let m=tick(20);
assert.equal(m.mining[0].work,4,'only non-spawning miners at source count as effective WORK');
assert.equal(m.mining[0].assignedWork,12);assert.equal(m.harvestPotential,8);
assert.equal(m.sourceTheoreticalRate,10,'theoretical source rate is independent of current WORK');
assert.equal(ctx.Memory.frontier.energy.tick,20);assert.equal(ctx.Memory.frontier.energy.rooms.R.latest.harvest,null,'missing event data never claims zero harvesting');
assert.equal(ctx.Memory.frontier.energy.rooms.R.windows[300].eta,null);
assert(ctx.Memory.frontier.telemetry.capturedAt>0);
ctx.Game.time=21;ctx.module.exports.tick([room]);assert.equal(ctx.Memory.frontier.energy.tick,21,'ledger observes before 20-tick monitor sampling return');
assert.equal(m.mining[0].stock,3200);assert.equal(m.mining[0].stockDelta,null);assert.equal(m.mining[0].backlogSince,20);
assert.equal(m.roads.planned,2);assert.equal(m.roads.built,1);assert.equal(m.roads.sites,1);assert.equal(m.roads.swampRemaining,0);
assert.equal(m.roads.routes[0].built,1);assert.equal(m.roads.routes[0].sites,1);
assert.equal(logs.length,0,'first backlog observation does not log an alarm');
drop.amount=1000;room.controller.progress+=100;m=tick(40);
assert.equal(m.mining[0].stockDelta,-200);assert.equal(m.mining[0].netStockRate,-10);assert.equal(m.mining[0].lastStockDecrease,40);assert.equal(m.mining[0].backlogSince,20);
assert.equal(m.upgradeRate,5);assert.equal(m.hauling.capacity,250);
hauler.fatigue=4;hauler.memory.stuck=8;m=tick(60);assert.equal(m.hauling.fatigued,1);assert.equal(m.hauling.stalled,0,'fatigue is not blocked traffic');
hauler.fatigue=0;hauler.memory.stuck=5;hauler.memory.moveAttempt=80;m=tick(80);assert.equal(m.hauling.stalled,1);
hauler.memory.moveAttempt=80;m=tick(100);assert.equal(m.hauling.stalled,0,'old movement failures do not count a legally idle carrier as blocked');
tick(120);assert(logs.some(s=>s.includes('source-backlog-s')),'persistent per-source congestion is logged after 100 ticks');
drop.amount=0;box.store.energy=800;hauler.memory.stuck=0;m=tick(140);
assert.equal(m.mining[0].backlogSince,null);assert(!ctx.Memory.frontier.telemetry.alerts['R:source-backlog-s']);
assert(logs.some(s=>s.includes('recovered R:source-backlog-s')));
for(let t=160;t<=1800;t+=20)tick(t);assert.equal(ctx.Memory.frontier.telemetry.rooms.R.history.length,60,'history is bounded');
box.store.energy=100;drop.amount=700;m=tick(1820);assert.equal(m.mining[0].backlogSince,1820,'ground backlog is detected even with a non-full nearby container');
console.log('PASS: in-position mining WORK, per-source stock and persistent backlog, net stock trend, fatigue vs blockage, road coverage, recovery alerts, bounded history');
