const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'public/logs.html'),'utf8');
const script=fs.readFileSync(path.join(__dirname,'public/logs.js'),'utf8');
const ids=['2026-09-25T09-15-00Z-test','2026-09-25T08-15-00Z-test','2026-09-24T08-15-00Z-test'];
function log(i,status='completed') {const startedAt=i===2?'2026-09-24T08:15:00Z':i===1?'2026-09-25T08:15:00Z':'2026-09-25T09:15:00Z';return {schemaVersion:1,id:ids[i],kind:i===0?'setup':'scheduled',startedAt,updatedAt:startedAt,completedAt:status==='running'?null:startedAt,status,title:'巡检 '+i,summary:'已记录本轮结果 '+i,game:null,findings:[{severity:'critical',title:'源侧积压',detail:'真实原因待验证',evidence:['tick73931000'],issue:4}],tasks:[{issue:4,title:'解决积压',status:'verifying',progress:'代码已修改，等待新窗口',next:'核查覆盖率',owner:'本轮协调者'}],actions:[{at:startedAt,description:'采样',status:'done',result:'取得新tick'}],checks:[{name:'长期能效',result:'pending',detail:'尚未满足完整窗口'}],next:['继续验证，不重复开发'],references:[{label:'工单',url:'https://github.com/AdamZmy/Automated-Screeps/issues/4'}]};}
const records=[log(0),log(1,'blocked'),log(2)];
const summary=r=>({id:r.id,kind:r.kind,startedAt:r.startedAt,updatedAt:r.updatedAt,completedAt:r.completedAt,status:r.status,title:r.title,summary:r.summary,tick:null,issueNumbers:[4]});
let failIndex=false,failDetail=false,stale=false,empty=false;const requests=[];
const dom=new JSDOM(html,{url:'https://screeps-energy-observatory.vercel.app/logs?id='+ids[1],runScripts:'outside-only',pretendToBeVisual:true});
dom.window.AbortController=AbortController;
dom.window.fetch=async raw=>{requests.push(raw);const url=new URL(raw,'https://test.invalid'),id=url.searchParams.get('id'),day=url.searchParams.get('day');if((failIndex&&!id)||(failDetail&&id))return {ok:false,json:async()=>({ok:false,error:{code:'FAIL',message:'上游暂不可用'}})};let data;if(id)data=records.find(x=>x.id===id);else data={schemaVersion:1,updatedAt:records[0].updatedAt,...(day?{day}:{days:empty?[]:['2026-09-25','2026-09-24']}),runs:empty?[]:records.filter(x=>!day||x.id.startsWith(day)).map(summary)};return {ok:true,json:async()=>({ok:true,source:'github',fetchedAt:'2026-09-25T10:00:00Z',stale,data})};};
const flush=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};
dom.window.eval(script);
(async()=>{
await flush();const d=dom.window.document;
assert.equal(d.getElementById('log-day').value,'2026-09-25');
assert.equal(d.querySelector('.run-title').textContent,'巡检 1');
assert.equal(d.querySelectorAll('.run-card').length,2);
assert.match(d.getElementById('run-detail').textContent,/代码已修改，等待新窗口/);
assert.match(d.getElementById('run-detail').textContent,/未观测/);
assert.equal(d.querySelector('.issue-link').href,'https://github.com/AdamZmy/Automated-Screeps/issues/4');
d.querySelector('[data-id="'+ids[0]+'"]').click();await flush();
assert.equal(new URL(dom.window.location).searchParams.get('id'),ids[0]);
assert.match(d.querySelector('.detail-note').textContent,/不是一次新的游戏状态巡检/);
d.getElementById('log-status').value='blocked';d.getElementById('log-status').dispatchEvent(new dom.window.Event('change'));await flush();
assert.equal(d.querySelectorAll('.run-card').length,1);assert.equal(d.querySelector('.run-title').textContent,'巡检 1');
d.getElementById('log-status').value='failed';d.getElementById('log-status').dispatchEvent(new dom.window.Event('change'));await flush();
assert.match(d.getElementById('run-list').textContent,/此筛选下没有/);assert.equal(d.querySelector('.run-title'),null);
d.getElementById('log-status').value='';d.getElementById('log-status').dispatchEvent(new dom.window.Event('change'));await flush();
failIndex=true;d.getElementById('logs-refresh').click();await flush();
assert.equal(d.querySelectorAll('.run-card').length,2);assert.match(d.getElementById('logs-notice').textContent,/刷新失败.*保留/);assert.equal(d.querySelector('.run-title').textContent,'巡检 0');
failIndex=false;failDetail=true;d.getElementById('logs-refresh').click();await flush();
assert.equal(d.querySelector('.run-title').textContent,'巡检 0');assert.match(d.getElementById('logs-notice').textContent,/详情刷新失败/);
d.querySelector('[data-id="'+ids[1]+'"]').click();await flush();assert.equal(d.querySelector('.run-title'),null,'wrong-run old detail must not appear');
failDetail=false;stale=true;d.getElementById('logs-refresh').click();await flush();assert.match(d.getElementById('logs-notice').textContent,/过时缓存/);
stale=false;records[1].title='<img src=x onerror="window.attacked=1">';records[1].findings[0].detail='<script>window.attacked=1</script>';records[1].references.push({label:'恶意链接',url:'javascript:alert(1)'});
d.getElementById('logs-refresh').click();await flush();assert.equal(d.querySelectorAll('#run-detail img,#run-detail script').length,0);assert.match(d.querySelector('.run-title').textContent,/<img/);assert.equal(d.querySelector('a[href^="javascript:"]'),null);assert.equal(dom.window.attacked,undefined);
d.getElementById('log-day').value='2026-09-24';d.getElementById('log-day').dispatchEvent(new dom.window.Event('change'));await flush();assert.equal(d.querySelector('.run-title').textContent,'巡检 2');assert.equal(d.querySelectorAll('.run-card').length,1);
dom.window.history.replaceState({},'','/logs?id='+ids[0]);dom.window.dispatchEvent(new dom.window.PopStateEvent('popstate'));await flush();assert.equal(d.querySelector('.run-title').textContent,'巡检 0');
empty=true;d.getElementById('log-day').value='';d.getElementById('log-day').dispatchEvent(new dom.window.Event('change'));await flush();assert.match(d.getElementById('run-list').textContent,/尚无巡检记录/);
assert.doesNotMatch(d.body.textContent,/NaN|undefined|Infinity/);
Object.defineProperty(d,'hidden',{value:true,configurable:true});const count=requests.length;d.dispatchEvent(new dom.window.Event('visibilitychange'));await flush();assert.equal(requests.length,count);assert.match(d.getElementById('sync-label').textContent,/后台暂停/);
assert.ok(requests.every(x=>x.startsWith('/api/inspections')),'log page never reads game telemetry');
dom.window.close();console.log('Logs UI verified: deep links, dates/status filters, correct detail identity, progress/evidence, missing observations, errors and stale retention, XSS safety, empty archive, visibility pause.');
})().catch(error=>{dom.window.close();console.error(error);process.exitCode=1;});
