/* UI verification only. Synthetic data never ships in public/. Run: node verify-ui.cjs */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { JSDOM } = require('jsdom');
const root = __dirname;
const html = fs.readFileSync(path.join(root,'public/index.html'),'utf8');
const script = fs.readFileSync(path.join(root,'public/app.js'),'utf8');
const context = { module:{exports:{}},Intl,Map,Number,Date };
vm.runInNewContext(script,context);
const {normalizeTelemetry} = context.module.exports;
const tick=73936000;
function fixture() {
  const window = (size,growth) => ({ tick,requestedTicks:size,observedTicks:300,coverage:300/size,warmingUp:size>300,G:growth,eta:growth/20,theoreticalRate:20,harvestRate:16,upgradeRate:growth-1,buildUsefulRate:1,expenseRate:12,operatingCostRate:1.5,inventoryDelta:600,inventoryDeltaRate:2,residual:-120,residualRate:-.4,imports:0,exports:0,balanceObservedTicks:300,inventoryObservedTicks:300,spawnRate:1,repairRate:.3,towerRate:0,linkLossRate:0,buildOtherRate:.2,totals:{upgrade:(growth-1)*300,buildUseful:300},eligible:size===300,blocked:size>300?['warmup-or-gap']:[],sustainedLow:false,utilizationRate:growth+1.3,utilization:(growth+1.3)/20,utilizationProductiveRate:growth,usefulOperatingCostRate:1.3,utilizationTheoreticalRate:20,utilizationObservedTicks:200,utilizationCoverage:200/size,utilizationWarmingUp:true,utilizationEligible:false,utilizationBlocked:['utilization-warmup-or-gap'],utilizationTarget:.9});
  return {ok:true,source:'screeps-api',fetchedAt:new Date().toISOString(),capturedAt:Date.now(),tick,version:'test-only',ledgerVersion:1,shard:'shard1',rooms:{W21N26:{tick,rcl:4,capacity:1300,spawnEnergy:920,storage:5600,mining:[{x:24,y:24,activeMiners:1,stock:1210,dropped:0,potential:10,buffer:1210,bufferCapacity:2000,netStockRate:-1.2,backlogSince:null},{x:16,y:42,activeMiners:1,stock:2800,dropped:800,potential:10,buffer:2000,bufferCapacity:2000,netStockRate:3.2,backlogSince:tick-220}],hauling:{count:3,loaded:2,stalled:0,fatigued:0,energy:750,capacity:1200},roads:{built:21,planned:24,sites:3,swampRemaining:0},construction:{extension:{sites:4,progress:8000,total:12000}},energy:{tick,capturedAt:Date.now(),inventory:{total:7400},latest:{complete:true,reasons:[]},windows:{300:window(300,9),1500:window(1500,3),6000:window(6000,1)},history:Array.from({length:15},(_,index)=>({from:tick-300+index*20,to:tick-280+index*20,ticks:20,observedTicks:20,upgrade:(2+index%4)*20,buildUseful:20,harvest:(14+index%3)*20,potential:400})),scope:{kind:'owned-room-physical',complete:true,remoteCreeps:0,reasons:[]},indicator:{status:'clear'}}},W22N26:{tick,rcl:1,energy:null}},alerts:{backlog:{room:'W21N26',code:'source-backlog-test',message:'矿点库存持续积压',since:tick-220,lastSeen:tick}}};
}
const payload=fixture();
payload.cpu={limit:20,bucket:10000,performance:{tick,samples:20,mean:4.2,max:7.1,memoryBytes:180000,stages:{memory:{perTick:.8},monitor:{perTick:.4}},roles:{hauler:{perTick:1.1}},movement:{deliverySwitches:{total:2},pathResets:{total:1}}}};
payload.rooms.W21N26.upkeep=2.833;
payload.rooms.W21N26.economy={usefulEnergyTarget:16.17,buildEnergyTarget:14.17,upgradeWorkTarget:2,reserveRate:0};
const normalized=normalizeTelemetry(payload,'W21N26');
assert.equal(normalized.windowSize,1500);
assert.equal(normalized.metrics.growth,3);
assert.equal(normalized.metrics.eta,.15);
assert.equal(normalized.metrics.utilizationRate,4.3);
assert.equal(normalized.metrics.utilization,.215);
assert.equal(normalized.utilizationObserved,200);
assert.equal(normalized.utilizationCoverage,200/1500);
assert.equal(normalized.metrics.renewalCeiling,1-2.833/20);
assert.equal(normalized.metrics.operating,1.5,'all known expense is not operating expense');
assert.equal(normalized.metrics.stock,2);
assert.equal(normalized.metrics.residual,-.4);
assert.equal(normalized.metrics.upgradeTotal,600);
assert.equal(normalized.history[0].growth,3);
assert.equal(normalized.history[0].theoretical,20);
assert.equal(normalized.ledgerVersion,1);
assert.equal(normalized.warmingUp,true);
const legacy=normalizeTelemetry({tick,rooms:{W21N26:{energy:600,history:[{t:tick,u:2}]}}});
assert.equal(legacy.hasLedger,false);
assert.equal(legacy.metrics.growth,null);
assert.equal(legacy.history.length,0);
assert.equal(legacy.metrics.utilization,null);
assert.equal(legacy.metrics.renewalCeiling,null);
const oldLedger=fixture();
for(const window of Object.values(oldLedger.rooms.W21N26.energy.windows))for(const key of Object.keys(window))if(key.startsWith('utilization')||key==='usefulOperatingCostRate')delete window[key];
const oldMetrics=normalizeTelemetry(oldLedger);
assert.equal(oldMetrics.metrics.growth,3);
assert.equal(oldMetrics.metrics.utilization,null,'old growth and expenses never synthesize a new metric');
assert.equal(oldMetrics.hasUtilization,false);
const fallback=fixture();fallback.rooms.W21N26.economy={upkeep:4};
assert.equal(normalizeTelemetry(fallback).metrics.renewalCeiling,.8);
fallback.rooms.W21N26.energy.windows[1500].theoreticalRate=0;
assert.equal(normalizeTelemetry(fallback).metrics.renewalCeiling,null,'zero potential cannot produce a ceiling');
const bad=fixture();bad.rooms.W21N26.energy.windows[1500].G=NaN;bad.rooms.W21N26.energy.windows[1500].operatingCostRate=Infinity;bad.rooms.W21N26.energy.history=[{to:tick,observedTicks:20}];
const missing=normalizeTelemetry(bad);
assert.equal(missing.metrics.growth,null);assert.equal(missing.metrics.operating,null);assert.equal(missing.history[0].growth,null,'absent history sums cannot become zero');
let response={status:200,body:payload};let requests=0;
const dom=new JSDOM(html,{url:'http://localhost',runScripts:'outside-only',pretendToBeVisual:true});
dom.window.fetch=async()=>{requests++;return {ok:response.status===200,status:response.status,json:async()=>response.body};};
dom.window.AbortController=AbortController;
dom.window.eval(script);
const flush=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
  await flush();await flush();
  const d=dom.window.document;
  assert.match(d.getElementById('cpu-summary').textContent,/4.20 \/ 20/);
  assert.match(d.getElementById('cpu-summary').textContent,/目标切换 \/ 受阻重算2 \/ 1/);
  assert.match(d.getElementById('cpu-stages').textContent,/持久数据解析0.80 CPU\/t/);
  assert.equal(d.getElementById('growth-value').textContent,'3.00');
  assert.equal(d.getElementById('utilization-value').textContent,'4.30');
  assert.equal(d.getElementById('growth-efficiency').textContent,'15.0%');
  assert.equal(d.getElementById('efficiency-value').textContent,'21.5%');
  assert.match(d.getElementById('efficiency-gap').textContent,/68.5 个百分点/);
  assert.match(d.getElementById('efficiency-ceiling').textContent,/85.8%.*未扣维修/);
  assert.match(d.getElementById('diagnostics-content').textContent,/总用能率尚未达到长期 90% 目标/);
  assert.match(d.getElementById('cost-coverage').textContent,/300 ticks/);
  assert.match(d.getElementById('budget-breakdown').textContent,/14.2 \/ 1.0 e\/t/);
  assert.equal(d.getElementById('operating-value').textContent,'1.5');
  assert.equal(d.getElementById('stock-value').textContent,'+2.0');
  assert.equal(d.getElementById('coverage-value').textContent,'13.3%');
  assert.match(d.getElementById('status-text').textContent,/预热/);
  assert.equal(d.querySelectorAll('.chart-series').length,3);
  assert.equal(d.querySelectorAll('.source-card').length,2);
  d.querySelector('[data-window="300"]').click();
  assert.equal(d.getElementById('growth-value').textContent,'9.00');
  assert.equal(d.getElementById('coverage-value').textContent,'66.7%');
  const chartHit=d.querySelector('.chart-hit');chartHit.dispatchEvent(new dom.window.FocusEvent('focus'));
  assert.match(d.querySelector('.chart-tooltip').textContent,/TICK/);
  chartHit.dispatchEvent(new dom.window.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));
  assert.match(d.querySelector('.chart-tooltip').textContent,/73,935,980/);
  const select=d.getElementById('room-select');select.value='W22N26';select.dispatchEvent(new dom.window.Event('change'));
  assert.equal(d.getElementById('growth-value').textContent,'—');assert.equal(d.querySelectorAll('.chart-series').length,0);
  select.value='W21N26';select.dispatchEvent(new dom.window.Event('change'));
  response={status:500,body:{ok:false,error:{code:'TEST_UNAVAILABLE',message:'test unavailable'}}};d.getElementById('refresh-button').click();await flush();await flush();
  assert.equal(d.getElementById('growth-value').textContent,'9.00');assert.match(d.getElementById('notice').textContent,/保留最近/);assert.match(d.getElementById('notice').textContent,/test unavailable/);
  const attack=fixture();attack.alerts.backlog.message='<img src=x onerror="window.attacked=true">';attack.stale=true;attack.upstreamError={message:'upstream test unavailable'};
  response={status:200,body:attack};d.getElementById('refresh-button').click();await flush();await flush();
  assert.equal(d.querySelectorAll('#diagnostics-content img').length,0);
  assert.match(d.getElementById('diagnostics-content').textContent,/<img/);
  assert.match(d.getElementById('status-text').textContent,/过时/);
  assert.match(d.getElementById('notice').textContent,/upstream test unavailable/);
  assert.doesNotMatch(d.body.textContent,/NaN|Infinity|undefined/);
  response={status:200,body:oldLedger};d.getElementById('refresh-button').click();await flush();await flush();
  assert.match(d.getElementById('cpu-stages').textContent,/等待分阶段/);
  assert.equal(d.getElementById('utilization-value').textContent,'—');
  assert.equal(d.getElementById('efficiency-value').textContent,'—');
  assert.equal(d.getElementById('growth-value').textContent,'9.00');
  assert.match(d.getElementById('diagnostics-content').textContent,/等待新版总用能账本/);
  const burst=fixture();const burstWindow=burst.rooms.W21N26.energy.windows[300];
  Object.assign(burstWindow,{utilizationRate:22,utilization:1.1,utilizationProductiveRate:9,usefulOperatingCostRate:13,utilizationObservedTicks:300,utilizationCoverage:1,utilizationWarmingUp:false,utilizationEligible:false,utilizationBlocked:['stock-drawdown']});
  burst.rooms.W21N26.energy.history.forEach(point=>Object.assign(point,{utilizationTicks:20,usedEnergy:440,utilizationPotential:400}));
  response={status:200,body:burst};d.getElementById('refresh-button').click();await flush();await flush();
  assert.equal(d.getElementById('efficiency-value').textContent,'110.0%','inventory-funded bursts must not be clamped');
  assert.match(d.getElementById('efficiency-gap').textContent,/持续性待验证/);
  assert.doesNotMatch(d.getElementById('diagnostics-content').textContent,/总用能率尚未达到长期 90% 目标/);
  assert.match(d.getElementById('diagnostics-content').textContent,/正在消耗既有库存/);
  assert.equal(d.querySelectorAll('.chart-series').length,4);
  assert.equal(d.getElementById('growth-efficiency').textContent,'45.0%');
  Object.defineProperty(d,'hidden',{configurable:true,value:true});d.dispatchEvent(new dom.window.Event('visibilitychange'));
  assert.match(d.getElementById('polling-label').textContent,/已暂停/);
  const before=requests;await flush();assert.equal(requests,before);
  dom.window.close();console.log('UI verified: same-coverage utilization, 90% target, independent development rate, renewal ceiling, missing new ledger, non-clamped bursts, expense coverage and budgets, null history, chart interaction, room/window controls, stale retention, upstream errors, text safety, hidden pause.');
})().catch(error=>{dom.window.close();console.error(error);process.exitCode=1;});
